In [2]:
import numpy as np
ar_id = np.arange(1,13)
print(ar_id)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [5]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [6]:
ar_id.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])