In [1]:
import numpy as np

In [3]:
max_is = np.array([[1,1,1],[1,1,1],[1,1,1]])
print (max_is)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
mx_1 = np.ones(5)
mx_1 .dtype


dtype('float64')

In [7]:
mx_2 = np.ones((3,4))

In [8]:
print(mx_2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
mx_3= np.ones((3,4),dtype=int)
print(mx_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 3.893e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
