In [3]:
import numpy as np

In [5]:
arra_1d =np.array([1,2,3,4])
print(arra_1d)

[1 2 3 4]


In [6]:
type(arra_1d)

numpy.ndarray

In [7]:
arra_1d.ndim

1

In [8]:
arra_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arra_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [10]:
arra_2d.ndim

2

In [11]:
arra_2d.shape

(2, 4)

In [12]:
arra_2d.dtype

dtype('int32')